post http://localhost:5000/api/login 
Content-Type: application/json

{
    "username": "ken",
    "password": "oicu812"
}
###

post http://localhost:5000/api/register 
Content-Type: application/json

{
    "username": "dex",
    "password": "oicu812"
}

###

get http://localhost:5000/api/users 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU2MDMwMTk5OX0.gskrJXO1YDcsvzO8RmFsD1H7EQV2o8GEsVANzLvk-ME